// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FiguresAction;
    
    private Gtk.Action AddClassFigureAction;
    
    private Gtk.Action AddStackFigureAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private MonoHotDraw.SteticComponent mhdcanvas;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FiguresAction = new Gtk.Action("FiguresAction", Mono.Unix.Catalog.GetString("Figures"), null, null);
        this.FiguresAction.ShortLabel = Mono.Unix.Catalog.GetString("Figures");
        w1.Add(this.FiguresAction, null);
        this.AddClassFigureAction = new Gtk.Action("AddClassFigureAction", Mono.Unix.Catalog.GetString("Add Class Figure"), null, null);
        this.AddClassFigureAction.ShortLabel = Mono.Unix.Catalog.GetString("Add Class Figure");
        w1.Add(this.AddClassFigureAction, null);
        this.AddStackFigureAction = new Gtk.Action("AddStackFigureAction", Mono.Unix.Catalog.GetString("Add StackFigure"), null, null);
        this.AddStackFigureAction.ShortLabel = Mono.Unix.Catalog.GetString("Add StackFigure");
        w1.Add(this.AddStackFigureAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FiguresAction' action='FiguresAction'><menuitem name='AddClassFigureAction' action='AddClassFigureAction'/><menuitem name='AddStackFigureAction' action='AddStackFigureAction'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.mhdcanvas = new MonoHotDraw.SteticComponent();
        this.mhdcanvas.Events = ((Gdk.EventMask)(256));
        this.mhdcanvas.Name = "mhdcanvas";
        this.vbox1.Add(this.mhdcanvas);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.mhdcanvas]));
        w3.Position = 1;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.AddClassFigureAction.Activated += new System.EventHandler(this.OnAddClassFigureActionActivated);
        this.AddStackFigureAction.Activated += new System.EventHandler(this.OnAddStackFigureActionActivated);
    }
}
