// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoHotDraw.Samples {
    
    
    public partial class MainWindow {
        
        private Gtk.UIManager UIManager;
        
        private Gtk.Action actoriconAction;
        
        private Gtk.Action actoriconAction1;
        
        private Gtk.Action actoriconAction2;
        
        private Gtk.Action connectioniconAction;
        
        private Gtk.Action usecaseiconAction;
        
        private Gtk.Action commenticonAction;
        
        private Gtk.Action FiguresAction;
        
        private Gtk.Action AddActor;
        
        private Gtk.Action AddUseCase;
        
        private Gtk.Action AddConnection;
        
        private Gtk.Action AddComment;
        
        private Gtk.Action FileAction;
        
        private Gtk.Action QuitAction;
        
        private Gtk.VBox vbox2;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.ScrolledWindow scrolledwindow;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoHotDraw.Samples.MainWindow
            this.UIManager = new Gtk.UIManager();
            Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
            this.actoriconAction = new Gtk.Action("actoriconAction", null, null, "actor_icon");
            w1.Add(this.actoriconAction, null);
            this.actoriconAction1 = new Gtk.Action("actoriconAction1", null, null, "actor_icon");
            w1.Add(this.actoriconAction1, null);
            this.actoriconAction2 = new Gtk.Action("actoriconAction2", null, null, "actor_icon");
            w1.Add(this.actoriconAction2, null);
            this.connectioniconAction = new Gtk.Action("connectioniconAction", null, null, "connection_icon");
            w1.Add(this.connectioniconAction, null);
            this.usecaseiconAction = new Gtk.Action("usecaseiconAction", null, null, "usecase_icon");
            w1.Add(this.usecaseiconAction, null);
            this.commenticonAction = new Gtk.Action("commenticonAction", null, null, "comment_icon");
            w1.Add(this.commenticonAction, null);
            this.FiguresAction = new Gtk.Action("FiguresAction", Mono.Unix.Catalog.GetString("Figures"), null, null);
            this.FiguresAction.ShortLabel = Mono.Unix.Catalog.GetString("Figures");
            w1.Add(this.FiguresAction, null);
            this.AddActor = new Gtk.Action("AddActor", Mono.Unix.Catalog.GetString("Add Actor"), null, null);
            this.AddActor.ShortLabel = Mono.Unix.Catalog.GetString("Add Actor");
            w1.Add(this.AddActor, null);
            this.AddUseCase = new Gtk.Action("AddUseCase", Mono.Unix.Catalog.GetString("Add UseCase"), null, null);
            this.AddUseCase.ShortLabel = Mono.Unix.Catalog.GetString("Add UseCase");
            w1.Add(this.AddUseCase, null);
            this.AddConnection = new Gtk.Action("AddConnection", Mono.Unix.Catalog.GetString("Add Connection"), null, null);
            this.AddConnection.ShortLabel = Mono.Unix.Catalog.GetString("Add Connection");
            w1.Add(this.AddConnection, null);
            this.AddComment = new Gtk.Action("AddComment", Mono.Unix.Catalog.GetString("Add Comment"), null, null);
            this.AddComment.ShortLabel = Mono.Unix.Catalog.GetString("Add Comment");
            w1.Add(this.AddComment, null);
            this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
            this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
            w1.Add(this.FileAction, null);
            this.QuitAction = new Gtk.Action("QuitAction", Mono.Unix.Catalog.GetString("_Salir"), null, "gtk-quit");
            this.QuitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Salir");
            w1.Add(this.QuitAction, null);
            this.UIManager.InsertActionGroup(w1, 0);
            this.AddAccelGroup(this.UIManager.AccelGroup);
            this.Name = "MonoHotDraw.Samples.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("MainWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child MonoHotDraw.Samples.MainWindow.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='FiguresAction' action='FiguresAction'><menuitem name='AddActor' action='AddActor'/><menuitem name='AddUseCase' action='AddUseCase'/><menuitem name='AddConnection' action='AddConnection'/><menuitem name='AddComment' action='AddComment'/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox2.Add(this.menubar1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.scrolledwindow = new Gtk.ScrolledWindow();
            this.scrolledwindow.CanFocus = true;
            this.scrolledwindow.Name = "scrolledwindow";
            this.scrolledwindow.ShadowType = ((Gtk.ShadowType)(1));
            this.vbox2.Add(this.scrolledwindow);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow]));
            w3.Position = 1;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 446;
            this.DefaultHeight = 300;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.AddActor.Activated += new System.EventHandler(this.OnAddActorActivated);
            this.AddUseCase.Activated += new System.EventHandler(this.OnAddUseCaseActivated);
            this.AddConnection.Activated += new System.EventHandler(this.OnAddConnectionActivated);
            this.AddComment.Activated += new System.EventHandler(this.OnAddCommentActivated);
            this.QuitAction.Activated += new System.EventHandler(this.OnQuitActionActivated);
        }
    }
}
